# Generated by Django 4.2.3 on 2023-08-17 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_dept_rename_autuor_accessrecord_author_emp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='comm',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
