# Generated by Django 4.2.3 on 2023-08-17 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_emp_comm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='comm',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
