# Generated by Django 4.2.3 on 2023-08-17 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_emp_comm'),
    ]

    operations = [
        migrations.AddField(
            model_name='dept',
            name='loc',
            field=models.CharField(default='banglore', max_length=100),
        ),
    ]
